### PR TITLE
Attach a path to errors where possible

### LINKED ISSUE #71: Errors from creating files / directories should include the path that was attempted
I've been using `tempdir` in a project of mine but since that's deprecated in favor of this crate I figured I'd file this issue here.

While trying to track down [an issue in Firefox CI](https://bugzilla.mozilla.org/show_bug.cgi?id=1396845) I wound up patching `tempdir` to return the path it tried to create as part of the error message when it failed:
https://github.com/luser/tempdir/commit/bc045d5e96c85074da83efdf7ca512a2cfd5826b

Without that patch the error was just "The system cannot find the path specified. (os error 3)" which didn't give me much to work with. With that patch I instead got "Error creating temp directory "z:\\build\\build\\src\\c\\Users\\task_1537988825\\AppData\\Local\\Temp\\sccache.HQRR1j9faz6I": The system cannot find the path specified. (os error 3)" which was much more useful.

It would be nice if we could do this in the tempfile crate as well.

### PR DESCRIPTION
**Pull request by KodrAus**
Closes #71 

Adds an internal extension trait that lets us attach a `PathBuf` as context to an `io::Error` from temporary paths and directories when operations on them fail. It's not going to catch cases where we touch the underlying `File` itself, but should be a little more helpful for diagnostics.

cc @luser @Stebalien

### CODE REVIEW

File: src/util.rs [hunk 1]
```diff
@@ -37,7 +39,9 @@ pub fn create_helper<F, R>(
 where
     F: Fn(PathBuf) -> io::Result<R>,
 {
-    for _ in 0..::NUM_RETRIES {
+    let num_retries = if random_len != 0 { ::NUM_RETRIES } else { 1 };
```
Comment (KodrAus) [inline src/util.rs]: While testing this I was playing with attempting to create a file I could guarantee already existed by setting `random_len` to `0`. That's a bit of a footgun because you'll effectively try create the file 2147483648 times before giving up. Setting `random_len` to `0` is pretty silly, but we might want to just panic or use a much smaller number of retries if the available entropy is too small. I thought I'd leave this here so we could think about it more.

File: src/error.rs [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+    fn cause(&self) -> Option<&error::Error> {
+        self.err.cause()
+    }
+}
+
+pub(crate) trait IoErrorExt {
+    fn with_path<P>(self, path: P) -> Self where P: Into<PathBuf>;
+}
+
+impl IoErrorExt for io::Error {
```
Comment (luser) [inline src/error.rs]: If you wanted to make the code slightly less verbose you could impl this on `io::Result` instead, and just put the `map_err` in this function.

File: src/util.rs (hunk 1 above)
Comment (Stebalien) [reply src/util.rs]: One try sounds reasonable, nice catch! I can see users wanting to *explicitly* specify the path of a temporary file (if they just want a file that's automatically cleaned up).

Really, we should probably set NUM_RETRIES to something sane like 256 but we can do that later.

File: src/error.rs (hunk 2 above)
Comment (KodrAus) [reply src/error.rs]: Good idea :+1:
